
tokenizer: !SimpleDFATokenizer()
    max_len: 1024

datasets: !make_binary_datasets()
    max_size: 21
    train_per: 0.9

DFA: !generate_random_binary_dfa()
    n_states: 4

model: !SimpleEncoder()
    n_tokens: 2 
    nlayers: 6
    use_xavier: True
